In [1]:
#Libraries Used
import pandas as pd
import numpy as np

In [4]:
#Constants
filename="data/year_2000.csv"

In [40]:
#Load dataset
data=pd.read_csv(filename,header=None,skiprows=[0,1])
data.drop(range(21,35),axis=1,inplace=True)
data.columns=['Year', 'Month', 'Day', 'Hour', 'Minute', 'DHI', 'DNI', 'GHI',
       'Clearsky_DHI', 'Clearsky_DNI', 'Clearsky_GHI', 'Dew_Point',
       'Temperature', 'Pressure', 'Relative_Humidity', 'Solar_Zenith_Angle',
       'Precipitable_Water', 'Snow_Depth', 'Wind_Direction', 'Wind_Speed',
       'Fill_Flag']

In [41]:
data.head()

,Year,Month,Day,Hour,Minute,DHI,DNI,GHI,Clearsky_DHI,Clearsky_DNI,...,Dew_Point,Temperature,Pressure,Relative_Humidity,Solar_Zenith_Angle,Precipitable_Water,Snow_Depth,Wind_Direction,Wind_Speed,Fill_Flag
0,Year,Month,Day,Hour,Minute,DHI,DNI,GHI,Clearsky DHI,Clearsky DNI,...,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Snow Depth,Wind Direction,Wind Speed,Fill Flag
1,2000,1,1,0,30,0,0,0,0,0,...,-3,16.68681858,1009.309814,24.77444661,175.6089068,0.822868198,0,355.9130249,3.736798048,0
2,2000,1,1,1,30,0,0,0,0,0,...,-3,15.9417887,1008.910156,25.81725984,170.4984323,0.812899109,0,0.221199036,3.702789068,0
3,2000,1,1,2,30,0,0,0,0,0,...,-3,15.27378364,1008.644226,26.84903711,156.8006524,0.798504359,0,5.518348694,3.614094734,0
4,2000,1,1,3,30,0,0,0,0,0,...,-3,14.65853875,1008.795288,27.80578118,143.1500899,0.775863682,0,10.75902557,3.487339973,0

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8761 entries, 0 to 8760
Data columns (total 21 columns):
Year                  8761 non-null object
Month                 8761 non-null object
Day                   8761 non-null object
Hour                  8761 non-null object
Minute                8761 non-null object
DHI                   8761 non-null object
DNI                   8761 non-null object
GHI                   8761 non-null object
Clearsky_DHI          8761 non-null object
Clearsky_DNI          8761 non-null object
Clearsky_GHI          8761 non-null object
Dew_Point             8761 non-null object
Temperature           8761 non-null object
Pressure              8761 non-null object
Relative_Humidity     8761 non-null object
Solar_Zenith_Angle    8761 non-null object
Precipitable_Water    8761 non-null object
Snow_Depth            8761 non-null object
Wind_Direction        8761 non-null object
Wind_Speed            8761 non-null object
Fill_Flag             8761 non-null object
dtypes: object(21)
memory usage: 1.4+ MB